#!/usr/bin/env python
import argparse
import logging
import os
import pathlib
import re
import sys
import tomllib

import utils
from typing import LiteralString

from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

DEFAULT_LOC_SOURCE_FILE = utils.LOC_DIR / "en-US.toml"
DEFAULT_HEADER_OUTPUT_FILE: pathlib.Path = utils.BUILD_DIR / "generated" / "autoinput_ui" / "core" / "localizationIds.h"
DEFAULT_SOURCE_OUTPUT_FILE = DEFAULT_HEADER_OUTPUT_FILE.with_suffix('.cpp')


def to_id_name(key: str) -> str:
    """Convert a dotted/camelCase localization key (e.g., 'app.name', 'windows.configEditor')
    into a C++ identifier constant name (e.g., 'APP_NAME_ID', 'WINDOWS_CONFIG_EDITOR_ID').
    """
    parts = key.split(".")
    processed_parts = []
    for part in parts:
        part = part.replace("-", "_")
        # insert underscore before capital letters (camelCase -> snake_case)
        part = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", part)
        processed_parts.append(part)
    combined = "_".join(processed_parts)
    combined = re.sub(r"_+", "_", combined).strip("_")
    return f"{combined.upper()}_ID"




@dataclass(frozen=True)
class LocalizationId:
    """Represents a localization key ID."""
    name: str
    id_name: str
    value: int


@dataclass
class LocalizationData:
    definitions: list[str] = field(default_factory=list)
    key_array_entries: list[str] = field(default_factory=list)

    @classmethod
    def generate(cls, loc_ids: list[LocalizationId]) -> 'LocalizationData':
        indent_space = 4
        definitions = []
        key_array_entries = []
        id_prefix = ' ' * indent_space
        key_array_prefix = ' ' * (indent_space * 2)
        for loc_id in loc_ids:
            definitions.append(f"{id_prefix}inline constexpr LocId {loc_id.id_name} = {loc_id.value};")
            key_array_entries.append(f'{key_array_prefix}"{loc_id.name}",')

        return cls(
            definitions=definitions,
            key_array_entries=key_array_entries,
        )

    def gen_defs_str(self, eol: str = "\n") -> str:
        return eol.join(self.definitions)

    def gen_key_array_entries_str(self, eol: str = "\n") -> str:
        return eol.join(self.key_array_entries)

def _get_localization_ids(keys: list[str]) -> list[LocalizationId]:
    loc_ids: list[LocalizationId] = []
    keys.sort()
    for idx, key in enumerate(keys):
        id_name = to_id_name(key)
        loc_ids.append(LocalizationId(name=key, id_name=id_name, value=idx))

    return loc_ids

def generate_header_source_content(keys: list[str], eol: str = "\n") -> tuple[str, str]:
    """Generates the C++ header and source file content for the given list of sorted keys."""
    loc_ids = _get_localization_ids(keys)
    data = LocalizationData.generate(loc_ids)

    header_lines = [
        "/**",
        " * @file localizationIds.h",
        " * @brief Auto-generated localization key IDs and matching helpers.",
        " * Generated by scripts/gen_localization_ids.py. Do not edit manually.",
        " */",
        "#ifndef INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "#define INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "#pragma once",
        "",
        '#include "autoinput/support/types.h"',
        "#include <array>",
        "#include <string_view>",
        "#include <algorithm>",
        "",
        "namespace autoinput::ui",
        "{",
        "using LocId = i32;",
        "}",
        "",
        "namespace autoinput::ui::LocalizationIds",
        "{",
        "    inline constexpr LocId INVALID_ID = -1;",
        "",
        *data.definitions,
        "",
        f"    inline constexpr LocId KEY_COUNT = {len(data.definitions)};",
        "",
        "    constexpr std::array<std::string_view, KEY_COUNT> KEYS = {",
        *data.key_array_entries,
        "};",
        "",
        "    /**",
        "     * @brief Match a localization ID to its TOML key string.",
        "     * @param id The localization ID.",
        "     * @return The key string_view, or empty string_view if invalid ID.",
        "     */",
        "    [[nodiscard]] inline constexpr std::string_view idToKey(LocId id) noexcept",
        "    {",
        "        if (id >= 0 && static_cast<size_t>(id) < KEYS.size())",
        "        {",
        '            return KEYS[static_cast<size_t>(id)];',
        "        }",
        '        return "";',
        "    }",
        "",
        "    /**",
        "     * @brief Match a TOML key string to its localization ID.",
        "     * @param key The key string.",
        "     * @return The localization ID, or INVALID_ID if not found.",
        "     */",
        "    [[nodiscard]] inline constexpr LocId keyToId(std::string_view key) noexcept",
        "    {",
        "        const auto it = std::lower_bound(KEYS.begin(), KEYS.end(), key);",
        "        if (it != KEYS.end() && *it == key)",
        "        {",
        "            return static_cast<LocId>(std::distance(KEYS.begin(), it));",
        "        }",
        "        return INVALID_ID;",
        "    }",
        "}",
        "",
        "namespace autoinput::ui",
        "{",
        "    namespace LocIds = LocalizationIds;",
        "}",
        "",
        "#endif // INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "",
    ]

    source_lines = [
        "/**",
        " * @file localizationIds.cpp",
        " * @brief Auto-generated localization key IDs and matching helpers.",
        " * Generated by scripts/gen_localization_ids.py. Do not edit manually.",
        " */",
        '#include "localizationIds.h"',
        "",
    ]

    header_content = eol.join(header_lines)
    source_content = eol.join(source_lines)
    return header_content, source_content


def check_and_update_file_contents(filepath: pathlib.Path, contents: str, filetype: LiteralString ['header', 'source'] ,
                                   key_count: int,
                                   check_only: bool) -> bool:
    if check_only:
        if not filepath.exists():
            logger.error(f"Output {filetype} file does not exist: {filepath}")
            return False
        try:
            existing = filepath.read_text(encoding="utf-8")
            if existing == contents:
                logger.info(f"Localization {filetype} {filepath} is up to date ({key_count} keys).")
                return True
            else:
                logger.error(f"Localization {filetype} {filepath} is out of date.")
                return False
        except Exception as e:
            logger.error(f"Failed to read existing {filetype} {filepath}: {e}")
            return False

    try:
        filepath.parent.mkdir(parents=True, exist_ok=True)
        # Check if identical to avoid bumping file modification time unnecessarily
        if filepath.exists():
            try:
                existing = filepath.read_text(encoding="utf-8")
                if existing == contents:
                    logger.info(f"Localization {filetype} {filepath} is already up to date ({key_count} keys).")
                    return True
            except Exception:
                pass

        with filepath.open("w", encoding="utf-8", newline="\n") as f:
            f.write(contents)
        logger.info(f"Successfully generated {filepath} with {key_count} localization IDs.")
        return True
    except Exception as e:
        logger.error(f"Failed to write {filetype} to {filepath}: {e}")
        return False


def generate(
    loc_file_path: pathlib.Path = DEFAULT_LOC_SOURCE_FILE,
    header_path: pathlib.Path = DEFAULT_HEADER_OUTPUT_FILE,
    source_path: pathlib.Path = DEFAULT_SOURCE_OUTPUT_FILE,
    check_only: bool = False,
    eol: str = "\n",
) -> bool:
    """Generates localizationIds.h from the given TOML file."""
    loc_file = utils.LocalizationFile.load_from_filepath(loc_file_path)
    if not loc_file.is_valid():
        logger.error(f"Localization file not found: {loc_file_path}")
        return False

    keys = loc_file.get_all_sorted_keys()
    if not keys:
        logger.error(f"No localization keys found in {loc_file_path}")
        return False

    # Check for duplicate generated ID names
    seen_ids = {}
    for key in keys:
        id_name = to_id_name(key)
        if id_name in seen_ids:
            logger.error(f"ID name collision: '{key}' and '{seen_ids[id_name]}' both produce '{id_name}'")
            return False
        seen_ids[id_name] = key

    header_content, source_content = generate_header_source_content(keys, eol=eol)
    key_count = len(keys)
    if not check_and_update_file_contents(header_path, header_content, 'header', key_count, check_only):
        return False
    return check_and_update_file_contents(source_path, source_content, 'source', key_count, check_only)


def main():
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(
        description="Generate C++ header file with constexpr localization IDs and matching functions.",
    )
    parser.add_argument(
        "--loc",
        type=pathlib.Path,
        default=DEFAULT_LOC_SOURCE_FILE,
        help=f"Path to source TOML file (default: {DEFAULT_LOC_SOURCE_FILE})",
    )
    parser.add_argument(
        "--header",
        type=pathlib.Path,
        default=DEFAULT_HEADER_OUTPUT_FILE,
        help=f"Path to output header file (default: {DEFAULT_HEADER_OUTPUT_FILE})",
    )
    parser.add_argument(
        "--source",
        type=pathlib.Path,
        default=DEFAULT_SOURCE_OUTPUT_FILE,
        help=f"Path to output source file (default: {DEFAULT_SOURCE_OUTPUT_FILE})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if output file is up to date without modifying it.",
    )

    args = parser.parse_args()
    success = generate(loc_file_path=args.loc, header_path=args.header, source_path=args.source, check_only=args.check)
    if not success:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
