#!/usr/bin/env python
import argparse
import logging
import pathlib
import sys

from .utils import (
    LOC_DIR,
    BUILD_DIR,
    LocKeySettings,
    LocalizationId,
    LocalizationFile,
    TomlKeyValue,
    to_loc_id_name,
    get_localization_ids,
)
from typing import LiteralString

from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

DEFAULT_LOC_SOURCE_FILE = LOC_DIR / "en-US.toml"
DEFAULT_HEADER_OUTPUT_FILE: pathlib.Path = BUILD_DIR / "generated" / "autoinput" / "support" / "localizationIds.h"
DEFAULT_SOURCE_OUTPUT_FILE = DEFAULT_HEADER_OUTPUT_FILE.with_suffix('.cpp')


@dataclass
class LocalizationData:
    definitions: list[str] = field(default_factory=list)
    key_array_entries: list[str] = field(default_factory=list)

    @classmethod
    def generate(cls, loc_ids: list[LocalizationId]) -> 'LocalizationData':
        indent_space = 4
        definitions: list[str] = []
        key_array_entries: list[str] = []
        id_prefix = ' ' * indent_space
        key_array_prefix = ' ' * (indent_space * 2)
        def get_settings_format_str(settings: LocKeySettings) -> str:
            if settings != LocKeySettings.Empty:
                results: list[str] = []
                if settings & LocKeySettings.Format:
                    results.append("LocKeySettings::Format")
                return "|".join(results)
            return "LocKeySettings::None"

        for loc_id in loc_ids:
            definitions.append(f"{id_prefix}inline constexpr LocId {loc_id.id_name} = {loc_id.value};")
            loc_value_str = f"{{ /*index*/{loc_id.id_name}, /*keyName*/\"{loc_id.name}\", /*settings*/{get_settings_format_str(loc_id.settings)} }}"
            definitions.append(f"{id_prefix}inline constexpr LocKey {loc_id.key_name}{loc_value_str};")
            key_array_entries.append(f'{key_array_prefix}{loc_id.key_name},')

        return cls(
            definitions=definitions,
            key_array_entries=key_array_entries,
        )

    def gen_defs_str(self, eol: str = "\n") -> str:
        return eol.join(self.definitions)

    def gen_key_array_entries_str(self, eol: str = "\n") -> str:
        return eol.join(self.key_array_entries)


def generate_header_source_content(key_values: list[TomlKeyValue], eol: str = "\n") -> tuple[str, str]:
    """Generates the C++ header and source file content for the given list of sorted keys."""
    loc_ids = get_localization_ids(key_values)
    data = LocalizationData.generate(loc_ids)

    header_lines = [
        "/**",
        " * @file localizationIds.h",
        " * @brief Auto-generated localization key IDs and matching helpers.",
        " * Generated by scripts/gen_localization_ids.py. Do not edit manually.",
        " */",
        "#ifndef INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "#define INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "#pragma once",
        "",
        '#include "autoinput/support/types.h"',
        "#include <algorithm>",
        "#include <array>",
        "#include <optional>",
        "#include <string_view>",
        "#include <ranges>",
        "",
        "namespace autoinput",
        "{",
        "    using LocId = i32;",
        "    enum class LocKeySettings : u8",
        "    {",
        "        None = 0,",
        "        Format = 1 << 0,",
        "    };",
        "    AUTOINPUT_ENABLE_ENUM_BITWISE_OPERATORS(LocKeySettings);",
        "",
        "    struct LocKey",
        "    {",
        "        LocId index;",
        "        std::string_view keyName;",
        "        LocKeySettings settings;",
        "        constexpr LocKey(const LocId index, const std::string_view keyName, const LocKeySettings settings)",
        "            : index{ index }",
        "            , keyName{ keyName }",
        "            , settings{ settings }",
        "        {",
        "        }",
        "",
        "        constexpr bool operator==(const LocKey&) const = default;",
        "        constexpr bool operator==(const LocId rhs) const { return index == rhs; }",
        "        constexpr bool operator==(const std::string_view rhs) const { return keyName == rhs; }",
        "    };",
        "}",
        "",
        "namespace autoinput::LocalizationIds",
        "{",
        "    inline constexpr LocId INVALID_ID = -1;",
        "    inline constexpr LocKey INVALID_KEY{ /*index*/INVALID_ID, /*keyName*/\"\", /*settings*/LocKeySettings::None };",
        "",
        *data.definitions,
        "",
        f"    inline constexpr LocId KEY_COUNT = {len(data.key_array_entries)};",
        "    constexpr std::array<LocKey, KEY_COUNT> KEYS = {",
        *data.key_array_entries,
        "    };",
        "",
        "    /**",
        "    * @brief Match a localization ID to its localization key.",
        "     * @param id The localization ID.",
        "     * @return The localization key, or an empty optional if invalid ID",
        "     */",
        "    [[nodiscard]] constexpr std::optional<LocKey> idToLocKey(const LocId id) noexcept",
        "    {",
        "        if (id >= 0 && static_cast<size_t>(id) < KEYS.size())",
        "        {",
        "            return KEYS[static_cast<size_t>(id)];",
        "        }",
        "        return std::nullopt;",
        "    }",
        "",
        "    /**",
        "     * @brief Match a localization ID to its TOML key string.",
        "     * @param id The localization ID.",
        "     * @return The key string_view, or empty string_view if invalid ID.",
        "     */",
        "    [[nodiscard]] constexpr std::string_view idToKey(const LocId id) noexcept",
        "    {",
        "        if (id >= 0 && static_cast<size_t>(id) < KEYS.size())",
        "        {",
        '            return KEYS[static_cast<size_t>(id)].keyName;',
        "        }",
        '        return "";',
        "    }",
        "",
        "    /**",
        "     * @brief Match a TOML key string to its localization ID.",
        "     * @param key The key string.",
        "     * @return The localization ID, or INVALID_ID if not found.",
        "     */",
        "    [[nodiscard]] constexpr LocId keyToId(const std::string_view key) noexcept",
        "    {",
        "        if (const auto it = std::ranges::lower_bound(KEYS, key, std::less{}, &LocKey::keyName);",
        "            it != KEYS.end() && *it == key)",
        "        {",
        "            return static_cast<LocId>(std::distance(KEYS.begin(), it));",
        "        }",
        "        return INVALID_ID;",
        "    }",
        "}",
        "",
        "namespace autoinput",
        "{",
        "    namespace LocIds = LocalizationIds;",
        "    using LocContainer = std::array<std::string_view, LocalizationIds::KEY_COUNT>;",
        "    using LocKeyContainer = std::array<LocKey, LocalizationIds::KEY_COUNT>;",
        "}",
        "",
        "#endif // INCLUDE_AUTOINPUT_UI_CORE_LOCALIZATION_IDS_H",
        "",
    ]

    source_lines = [
        "/**",
        " * @file localizationIds.cpp",
        " * @brief Auto-generated localization key IDs and matching helpers.",
        " * Generated by scripts/gen_localization_ids.py. Do not edit manually.",
        " */",
        '#include "localizationIds.h"',
        "",
    ]

    header_content = eol.join(header_lines)
    source_content = eol.join(source_lines)
    return header_content, source_content


def check_and_update_file_contents(filepath: pathlib.Path, contents: str, filetype: LiteralString ['header', 'source'] ,
                                   key_count: int,
                                   check_only: bool) -> bool:
    if check_only:
        if not filepath.exists():
            logger.error(f"Output {filetype} file does not exist: {filepath}")
            return False
        try:
            existing = filepath.read_text(encoding="utf-8")
            if existing == contents:
                logger.info(f"Localization {filetype} {filepath} is up to date ({key_count} keys).")
                return True
            else:
                logger.error(f"Localization {filetype} {filepath} is out of date.")
                return False
        except Exception as e:
            logger.error(f"Failed to read existing {filetype} {filepath}: {e}")
            return False

    try:
        filepath.parent.mkdir(parents=True, exist_ok=True)
        # Check if identical to avoid bumping file modification time unnecessarily
        if filepath.exists():
            try:
                existing = filepath.read_text(encoding="utf-8")
                if existing == contents:
                    logger.info(f"Localization {filetype} {filepath} is already up to date ({key_count} keys).")
                    return True
            except Exception:
                pass

        with filepath.open("w", encoding="utf-8", newline="\n") as f:
            f.write(contents)
        logger.info(f"Successfully generated {filepath} with {key_count} localization IDs.")
        return True
    except Exception as e:
        logger.error(f"Failed to write {filetype} to {filepath}: {e}")
        return False


def generate(
    loc_file_path: pathlib.Path = DEFAULT_LOC_SOURCE_FILE,
    header_path: pathlib.Path = DEFAULT_HEADER_OUTPUT_FILE,
    source_path: pathlib.Path = DEFAULT_SOURCE_OUTPUT_FILE,
    check_only: bool = False,
    eol: str = "\n",
) -> bool:
    """Generates localizationIds.h from the given TOML file."""
    loc_file = LocalizationFile.load_from_filepath(loc_file_path)
    if not loc_file.is_valid():
        logger.error(f"Localization file not found: {loc_file_path}")
        return False

    key_values = loc_file.get_sorted_key_value_pairs()
    # keys = loc_file.get_all_sorted_keys()
    if not key_values:
        logger.error(f"No localization keys found in {loc_file_path}")
        return False

    # Check for duplicate generated ID names
    seen_ids = {}
    for key, _ in key_values:
        id_name = to_loc_id_name(key)
        if id_name in seen_ids:
            logger.error(f"ID name collision: '{key}' and '{seen_ids[id_name]}' both produce '{id_name}'")
            return False
        seen_ids[id_name] = key

    header_content, source_content = generate_header_source_content(key_values, eol=eol)
    key_count = len(key_values)
    if not check_and_update_file_contents(header_path, header_content, 'header', key_count, check_only):
        return False
    return check_and_update_file_contents(source_path, source_content, 'source', key_count, check_only)


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate C++ header file with constexpr localization IDs and matching functions.",
    )
    _ = parser.add_argument(
        "--loc",
        type=pathlib.Path,
        default=DEFAULT_LOC_SOURCE_FILE,
        help=f"Path to source TOML file (default: {DEFAULT_LOC_SOURCE_FILE})",
    )
    _ = parser.add_argument(
        "--header",
        type=pathlib.Path,
        default=DEFAULT_HEADER_OUTPUT_FILE,
        help=f"Path to output header file (default: {DEFAULT_HEADER_OUTPUT_FILE})",
    )
    _ = parser.add_argument(
        "--source",
        type=pathlib.Path,
        default=DEFAULT_SOURCE_OUTPUT_FILE,
        help=f"Path to output source file (default: {DEFAULT_SOURCE_OUTPUT_FILE})",
    )
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="Check if output file is up to date without modifying it.",
    )
    return parser


def main():
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    args = get_parser().parse_args()
    success = generate(loc_file_path=args.loc, header_path=args.header, source_path=args.source, check_only=args.check)
    if not success:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
