name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "resources/**"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "resources/**"

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DAUTOINPUT_BUILD_TESTS=ON -DAUTOINPUT_BUILD_TRAY=ON -DAUTOINPUT_BUILD_UI=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --output-on-failure -C Release
